---
- name:   Install App
  hosts: tag_Name_APP
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
       
    - name: Start a container
      docker_container:
        name: game
        image: volat/game-2048:3
        state: started
        restart: yes
        ports:
          - "80:80"
        volumes: 
          - "game:/usr/share/nginx/html"
                
    - name: Check by url
      uri:
        url: http://localhost
        return_content: yes
      register: this
    - debug: 
        msg: "{{ this }}"      