---  
- name:   Install servers
  hosts: tag_Env_Prod
  become: yes
  gather_facts: no
  become_method: sudo
  pre_tasks:
    - name: 'install python'
      raw: sudo apt-get -y install python
    
    - name: Apt update
      apt:
        update_cache: yes   
    - name: Upgrade all packages to the latest version
      apt:
        name: "*"
        force_apt_get: yes
        state: latest    
